version: '3'

services:
  minecraft:
    image: itzg/minecraft-server:multiarch
    container_name: "mc"
    ports:
      - "25565:25565"
    #volumes:
    #  - "./data:/data"
    environment:
      MEMORY: "2G"
      EULA: "TRUE"
      TYPE: "SPIGOT"
      SPIGOT_DOWNLOAD_URL: "https://cdn.getbukkit.org/spigot/spigot-1.15.2.jar"
      VERSION: "1.15.1"
      WORLD: "https://github.com/leomelki/LoupGarou/raw/master/maps/lg_village.zip"
      MODS: "https://github.com/dmulloy2/ProtocolLib/releases/download/4.5.1/ProtocolLib.jar,https://github.com/leomelki/LoupGarou/releases/download/1.1.0/LoupGarou.v1.1.0.jar"
      MOTD: "I'm back bitches"
      OPS: "Atheros33"
      OVERRIDE_SERVER_PROPERTIES: "true"
    tty: true
    stdin_open: true
    restart: always

volumes:
  mc: {}
